name: Build 
on:
  push:
    branches:
      - main
jobs:
  build:
    name: Run unit tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v1
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
      - name: Set Up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.16
      - name: Set Up Python
        uses: actions/setup-python@v2
        with:
          python-version: 2.7
      - name: Update Docker Images
        uses: magefile/mage-action@v1
        with:
          version: latest
          args: ci:build
      - name: Run Code Coverage
        uses: magefile/mage-action@v1
        with:
          version: latest
          args: coverage
      - name: Push Code Coverage
        uses: codecov/codecov-action@v1
        with:
          files: coverage.txt