name: Windows - A workflow for testing lodestar bazel rules
on:
  pull_request:
    branches:
      - main
jobs:
  test:
    name: Run Bazel rules
    runs-on: windows-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v1
      - name: Run Bazel Rules
        uses: magefile/mage-action@v1
        with:
          version: latest
          args: runRules
        env:
          GIT_USER: ${{ secrets.GIT_USER }}
          GIT_TOKEN: ${{ secrets.GIT_TOKEN }}
          YAML_KEYS: "tag=1234567"