name: Test Code
on:
  pull_request:
    branches:
      - main
jobs:
  test:
    name: Run tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v1
      - name: Run Code Coverage
        uses: magefile/mage-action@v1
        with:
          version: latest
          args: coverage