name: Test Bazel Rules
on:
  pull_request:
    branches:
      - main
jobs:
  test:
    name: Test Bazel rules
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout Code
        uses: actions/checkout@v1
      - name: Run Bazel Rules
        uses: magefile/mage-action@v1
        with:
          version: latest
          args: runRules
        env:
          GIT_USER: ${{ secrets.GIT_USER }}
          GIT_TOKEN: ${{ secrets.GIT_TOKEN }}