name: A workflow for running lodestar tests
on:
  push:
    branches-ignore:
      - main
  pull_request:
    branches:
      - main
jobs:
  test:
    name: Run unit tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: run internal package unit tests
        run: ./bazelisk test //internal/...
#      - name: run main file unit tests
#        run: ./bazelisk test //cmd/...