name: A workflow for running lodestar tests
on:
  push:
    branches-ignore:
      - main
  pull_request:
    branches:
      - main
jobs:
  test:
    name: Run unit tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v1
      - name: Run Code Coverage
        uses: magefile/mage-action@v1
        with:
          version: latest
          args: coverage
      - name: Push Code Coverage
        uses: codecov/codecov-action@v1
        with:
          files: coverage.txt